"use client";

import { AlertCircle, CheckCircle2, LoaderCircle, Save } from "lucide-react";
import { useActionState } from "react";
import { createCommitmentAction, updateCommitmentAction, type CommitmentActionState } from "@/app/admin/sponsor-deliverables/actions";

type Commitment = { id: string; sponsorId: string; kind: string; title: string; category: string; description: string; ownerUserId: string | null; dueDate: string | null; status: string; totalQuantity: number; completedQuantity: number; proofUrl: string | null; notes: string; visibleToSponsor: boolean };
const initialState: CommitmentActionState = { message: "", status: "idle" };
const inputClass = "rounded-md border border-slate-200 px-3 py-2 text-sm text-acv-ink";

export function CommitmentForm({ commitment, mode, sponsors, owners }: { commitment?: Commitment; mode: "create" | "update"; sponsors: Array<{ id: string; name: string }>; owners: Array<{ id: string; name: string }> }) {
  const [state, action, pending] = useActionState(mode === "create" ? createCommitmentAction : updateCommitmentAction, initialState);
  return <form action={action} className="grid gap-3">
    {commitment ? <input name="commitmentId" type="hidden" value={commitment.id} /> : null}
    <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Sponsor</span><select className={inputClass} defaultValue={commitment?.sponsorId ?? sponsors[0]?.id} name="sponsorId" required>{sponsors.map((sponsor) => <option key={sponsor.id} value={sponsor.id}>{sponsor.name}</option>)}</select></label><label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Commitment type</span><select className={inputClass} defaultValue={commitment?.kind ?? "benefit"} name="kind"><option value="benefit">Benefit owed to sponsor</option><option value="deliverable">Deliverable expected from sponsor</option></select></label></div>
    <label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Title</span><input className={inputClass} defaultValue={commitment?.title} name="title" required /></label>
    <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Category</span><input className={inputClass} defaultValue={commitment?.category} list="commitment-categories" name="category" required /><datalist id="commitment-categories"><option value="Brand visibility" /><option value="Social media" /><option value="Hospitality" /><option value="Stand activation" /><option value="Stage appearance" /><option value="Press" /><option value="Brand assets" /><option value="Reporting" /></datalist></label><label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Owner</span><select className={inputClass} defaultValue={commitment?.ownerUserId ?? ""} name="ownerUserId"><option value="">Unassigned</option>{owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Due date</span><input className={inputClass} defaultValue={commitment?.dueDate ?? ""} name="dueDate" type="date" /></label><label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Status</span><select className={inputClass} defaultValue={commitment?.status ?? "planned"} name="status"><option value="planned">Planned</option><option value="waiting_sponsor">Waiting for sponsor</option><option value="received">Received</option><option value="in_production">In production</option><option value="delivered">Delivered</option><option value="validated">Validated</option><option value="blocked">Blocked</option></select></label></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Quantity promised</span><input className={inputClass} defaultValue={commitment?.totalQuantity ?? 1} min="1" name="totalQuantity" type="number" /></label><label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Quantity completed</span><input className={inputClass} defaultValue={commitment?.completedQuantity ?? 0} min="0" name="completedQuantity" type="number" /></label></div>
    <label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Description</span><textarea className="min-h-20 rounded-md border border-slate-200 px-3 py-2 text-sm" defaultValue={commitment?.description} name="description" /></label>
    <label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Proof link</span><input className={inputClass} defaultValue={commitment?.proofUrl ?? ""} name="proofUrl" placeholder="https://…" type="url" /></label>
    <label className="grid gap-2"><span className="text-sm font-semibold text-slate-700">Internal notes</span><textarea className="min-h-20 rounded-md border border-slate-200 px-3 py-2 text-sm" defaultValue={commitment?.notes} name="notes" /></label>
    <label className="inline-flex items-center gap-2 text-sm font-semibold text-slate-700"><input defaultChecked={commitment?.visibleToSponsor ?? true} name="visibleToSponsor" type="checkbox" />Visible in the sponsor portal</label>
    {state.message ? <p className={`inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-semibold ${state.status === "error" ? "bg-rose-50 text-rose-800" : "bg-emerald-50 text-emerald-800"}`}>{state.status === "error" ? <AlertCircle className="size-4" /> : <CheckCircle2 className="size-4" />}{state.message}</p> : null}
    <button className="inline-flex w-fit items-center gap-2 rounded-md bg-acv-ink px-4 py-2 text-sm font-bold text-white disabled:bg-slate-400" disabled={pending}>{pending ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}{pending ? "Saving" : mode === "create" ? "Add commitment" : "Save changes"}</button>
  </form>;
}
